export const ADD_PROJETO = 'ADD_PROJETO';
export const ALTERAR_PROJETO = 'ALTERAR_PROJETO';
export const REMOVER_PROJETO = 'REMOVER_PROJETO';
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS';

export const NOTIFICAR = 'NOTIFICAR';

export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS';
export const ADICIONAR_TAREFA = '	ADICIONAR_TAREFA';
